### ISSUE TITLE
Is there functionality for rejoining the cluster when a node restarts?

### ISSUE THREAD

**Issue by GrantSeltzer** [hashicorp/memberlist#80]
Lets say a node is running on a computer that goes down for a given amount of time, is there functionality built into this library to rejoin the cluster it was part of?

First thing that comes to mind is just saving one or more of the ip's of other nodes in a file, but there's probably a more intuitive way of doing this.

I know this seems like a bit of a lazy question, I did look through the code, I just want to make sure :)

**Comment by slackpad** [comment]
Hi @GrantSeltzer this currently isn't baked into memberlist itself. This is usually handled at a higher level. For example, [Serf](https://github.com/hashicorp/serf) keeps state on disk that lets it restart and rejoin the cluster. Since this is something that doesn't have a clear good default policy, and this is a pretty low-level library, I'd hesitate to add it here.

**Comment by GrantSeltzer** [comment]
That's what I figured. What about in some highly configurable manner similar to how configs are created for the cluster? I'll have to take a look in Serf. 

I think i'm going to attempt this in some modular way for the project i'm using memberlist in, I'll be sure to bring it to your attention when that's complete. 

Thanks!

**Comment by slackpad** [comment]
It's usually done after memberlist is set up, and Serf has different policies if the join succeeds or not (keep trying to join X vs. fail if you can't join Y) and can be given a list of either policy, so it would add a lot of complexity to memberlist to make that configurable. I'd definitely be interested in taking a look at your project!
